"""empty message

Revision ID: 750e78ec133c
Revises: 
Create Date: 2022-05-17 17:21:49.385764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '750e78ec133c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_copy')
    op.drop_table('flight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('flight_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('flight_depcity', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flight_arrcity', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flight_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('flight_date', mysql.DATETIME(), nullable=False),
    sa.Column('flight_discount', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('flight_source', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('flight_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('flight_copy',
    sa.Column('flight_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('flight_depcity', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flight_arrcity', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flight_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('flight_date', mysql.DATETIME(), nullable=False),
    sa.Column('flight_discount', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('flight_source', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flight_url', mysql.LONGTEXT(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('flight_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
