"""empty message

Revision ID: 9c297a643c06
Revises: 6783eda12c52
Create Date: 2022-05-21 12:04:51.587463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c297a643c06'
down_revision = '6783eda12c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('source', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'source')
    # ### end Alembic commands ###
